apiVersion: v1
kind: Service
metadata:
  name: goecommerce-service
spec:
  type: NodePort
  selector:
    app: goecommerce  # This name must exactly match the matchLabels of the Deployment
  ports:
    - port: 80         # The Service will receive requests on this port
      targetPort: 5000 # Your Go app is running on this port inside the container
      nodePort: 30080  # We will access it from our local machine using this port